name: gcp-cloudrun-deploy
on: 
  push: 
    branches:
      - dev
      - feature
      - cloudrun-test

  pull_request:
    branches:
      - main
env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: gitactions 
  REGION: asia-south1 
  ALLOW_UNAUTHENTICATED: true
  MIN_INSTANCES: 1
  MAX_INSTANCES: 3
  CPU: 1
  MEMORY: 512 MiB
  PLATFORM: 

jobs:
  checkout-build-push-deploy: 
    name: "checkout build push deploy"
    runs-on: ubuntu-latest
    steps:
      - name: "1 -> checkout code from github"
        uses: actions/checkout@master

      - name: "2 -> setup gcloud sdk/cli"
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_SERVERLESS_SVCACCT_EMAIL }}
          service_account_key: ${{ secrets.GCP_SERVERLESS_SVCACCT_CREDENTIALS_KEY }}
          export_default_credentials: true

      - name: "2.5 -> check gcloud setup"
        run: |
         gcloud info

      - name: "3 -> configure docker"
        run: |
          gcloud auth configure-docker

      - name: "4 -> build and tag the container image using the Dockerfile from the source repo"
        run: |
          gcloud build -t gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{github.sha}} .
          gcloud push gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{github.sha}}

      - name: "5 -> deploy the conatiner image to  cloud run"
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --region ${{ env.REGION }} \
            --image gcr.io/${{env.GCP_PROJECT_ID}}/${{env.SERVICE_NAME}}:${{github.sha}} \
            --allow-unauthenticated ${{env.ALLOW_UNAUTHENTICATED}} \
            --quiet \
            --min-instances ${{ env.MIN_INSTANCES }} \
            --max-instances ${{ env.MAX_INSTANCES }} \
            --cpu ${{ env.CPU }} \
            --memory ${{ env.MEMORY }} \
            --labels 'tag=${{ github.sha }}'




 

    